// =====================================================================
//  القائمة القياسية لأقسام وفحوص المختبر الطبي في المستشفى
//  TEa: حدود القبول الكلية المسموح بها (%). المصدر الأساسي: CLIA 2024 PT limits
//  للفحوص ذات الحد المطلق حُوِّل الحد إلى % عند مستوى القرار السريري المذكور.
//  راجع القيم واعتمدها حسب سياسة الجودة في مختبرك قبل الاستخدام.
// =====================================================================
export const SEED = [
  { dept: 'الكيمياء السريرية', tests: [
    { name: 'Glucose', code: 'GLU', unit: 'mg/dL', tea: 8, src: 'CLIA 2024 (±8% or 6 mg/dL)', dec: 0 },
    { name: 'Urea (BUN)', code: 'BUN', unit: 'mg/dL', tea: 9, src: 'CLIA 2024 (±9% or 2 mg/dL)', dec: 1 },
    { name: 'Creatinine', code: 'CREA', unit: 'mg/dL', tea: 10, src: 'CLIA 2024 (±10% or 0.2 mg/dL)', dec: 2 },
    { name: 'Uric Acid', code: 'UA', unit: 'mg/dL', tea: 10, src: 'CLIA 2024', dec: 1 },
    { name: 'Sodium', code: 'NA', unit: 'mmol/L', tea: 3, src: 'CLIA 2024 (±4 mmol/L @140)', dec: 0 },
    { name: 'Potassium', code: 'K', unit: 'mmol/L', tea: 7, src: 'CLIA 2024 (±0.3 mmol/L @4.2)', dec: 1 },
    { name: 'Chloride', code: 'CL', unit: 'mmol/L', tea: 5, src: 'CLIA 2024', dec: 0 },
    { name: 'Total CO2 (Bicarbonate)', code: 'CO2', unit: 'mmol/L', tea: 20, src: 'CLIA 2024', dec: 0 },
    { name: 'Calcium (Total)', code: 'CA', unit: 'mg/dL', tea: 10, src: 'CLIA 2024 (±1.0 mg/dL @10)', dec: 1 },
    { name: 'Phosphorus', code: 'PHOS', unit: 'mg/dL', tea: 10, src: 'CLIA 2024 (±10% or 0.3 mg/dL)', dec: 1 },
    { name: 'Magnesium', code: 'MG', unit: 'mg/dL', tea: 15, src: 'CLIA 2024', dec: 1 },
    { name: 'Total Protein', code: 'TP', unit: 'g/dL', tea: 8, src: 'CLIA 2024', dec: 1 },
    { name: 'Albumin', code: 'ALB', unit: 'g/dL', tea: 8, src: 'CLIA 2024', dec: 1 },
    { name: 'Total Bilirubin', code: 'TBIL', unit: 'mg/dL', tea: 20, src: 'CLIA 2024 (±20% or 0.4 mg/dL)', dec: 2 },
    { name: 'Direct Bilirubin', code: 'DBIL', unit: 'mg/dL', tea: 20, src: 'Internal / BV', dec: 2 },
    { name: 'ALT (SGPT)', code: 'ALT', unit: 'U/L', tea: 15, src: 'CLIA 2024 (±15% or 6 U/L)', dec: 0 },
    { name: 'AST (SGOT)', code: 'AST', unit: 'U/L', tea: 15, src: 'CLIA 2024 (±15% or 6 U/L)', dec: 0 },
    { name: 'Alkaline Phosphatase', code: 'ALP', unit: 'U/L', tea: 20, src: 'CLIA 2024', dec: 0 },
    { name: 'GGT', code: 'GGT', unit: 'U/L', tea: 15, src: 'CLIA 2024 (±15% or 5 U/L)', dec: 0 },
    { name: 'LDH', code: 'LDH', unit: 'U/L', tea: 15, src: 'CLIA 2024', dec: 0 },
    { name: 'Creatine Kinase (CK)', code: 'CK', unit: 'U/L', tea: 20, src: 'CLIA 2024', dec: 0 },
    { name: 'Amylase', code: 'AMY', unit: 'U/L', tea: 20, src: 'CLIA 2024', dec: 0 },
    { name: 'Lipase', code: 'LIP', unit: 'U/L', tea: 20, src: 'Internal / BV', dec: 0 },
    { name: 'Total Cholesterol', code: 'CHOL', unit: 'mg/dL', tea: 10, src: 'CLIA 2024', dec: 0 },
    { name: 'Triglycerides', code: 'TG', unit: 'mg/dL', tea: 15, src: 'CLIA 2024', dec: 0 },
    { name: 'HDL Cholesterol', code: 'HDL', unit: 'mg/dL', tea: 20, src: 'CLIA 2024 (±20% or 6 mg/dL)', dec: 0 },
    { name: 'LDL Cholesterol (Direct)', code: 'LDL', unit: 'mg/dL', tea: 20, src: 'CLIA 2024', dec: 0 },
    { name: 'Iron', code: 'FE', unit: 'µg/dL', tea: 15, src: 'CLIA 2024', dec: 0 },
    { name: 'TIBC', code: 'TIBC', unit: 'µg/dL', tea: 20, src: 'CLIA 2024', dec: 0 },
    { name: 'C-Reactive Protein (CRP)', code: 'CRP', unit: 'mg/L', tea: 20, src: 'Internal / RCPA', dec: 1 },
    { name: 'HbA1c', code: 'A1C', unit: '%', tea: 8, src: 'CLIA 2024', dec: 1 },
    { name: 'Ammonia', code: 'NH3', unit: 'µmol/L', tea: 20, src: 'CLIA 2024', dec: 0 },
    { name: 'Lactate', code: 'LAC', unit: 'mmol/L', tea: 15, src: 'Internal / BV', dec: 1 },
  ]},
  { dept: 'أمراض الدم', tests: [
    { name: 'WBC', code: 'WBC', unit: '×10³/µL', tea: 10, src: 'CLIA 2024', dec: 2 },
    { name: 'RBC', code: 'RBC', unit: '×10⁶/µL', tea: 4, src: 'CLIA 2024', dec: 2 },
    { name: 'Hemoglobin', code: 'HGB', unit: 'g/dL', tea: 4, src: 'CLIA 2024', dec: 1 },
    { name: 'Hematocrit', code: 'HCT', unit: '%', tea: 4, src: 'CLIA 2024', dec: 1 },
    { name: 'MCV', code: 'MCV', unit: 'fL', tea: 5, src: 'Internal / BV', dec: 1 },
    { name: 'MCH', code: 'MCH', unit: 'pg', tea: 5, src: 'Internal / BV', dec: 1 },
    { name: 'MCHC', code: 'MCHC', unit: 'g/dL', tea: 5, src: 'Internal / BV', dec: 1 },
    { name: 'RDW', code: 'RDW', unit: '%', tea: 10, src: 'Internal / BV', dec: 1 },
    { name: 'Platelets', code: 'PLT', unit: '×10³/µL', tea: 25, src: 'CLIA 2024', dec: 0 },
    { name: 'MPV', code: 'MPV', unit: 'fL', tea: 10, src: 'Internal / BV', dec: 1 },
    { name: 'Reticulocytes', code: 'RET', unit: '%', tea: 30, src: 'CLIA 2024', dec: 2 },
    { name: 'ESR', code: 'ESR', unit: 'mm/hr', tea: 25, src: 'Internal', dec: 0 },
  ]},
  { dept: 'التخثر', tests: [
    { name: 'Prothrombin Time (PT)', code: 'PT', unit: 'sec', tea: 15, src: 'CLIA 2024', dec: 1 },
    { name: 'INR', code: 'INR', unit: '', tea: 15, src: 'CLIA 2024 (as PT)', dec: 2 },
    { name: 'APTT', code: 'APTT', unit: 'sec', tea: 15, src: 'CLIA 2024', dec: 1 },
    { name: 'Fibrinogen', code: 'FIB', unit: 'mg/dL', tea: 20, src: 'CLIA 2024', dec: 0 },
    { name: 'D-Dimer', code: 'DDIM', unit: 'µg/mL FEU', tea: 20, src: 'Internal', dec: 2 },
    { name: 'Thrombin Time', code: 'TT', unit: 'sec', tea: 15, src: 'Internal', dec: 1 },
  ]},
  { dept: 'المناعة والهرمونات', tests: [
    { name: 'TSH', code: 'TSH', unit: 'µIU/mL', tea: 20, src: 'CLIA 2024 (±20% or 0.2)', dec: 2 },
    { name: 'Free T4', code: 'FT4', unit: 'ng/dL', tea: 15, src: 'CLIA 2024 (±15% or 0.3 ng/dL)', dec: 2 },
    { name: 'Free T3', code: 'FT3', unit: 'pg/mL', tea: 20, src: 'Internal / BV', dec: 2 },
    { name: 'Total T4', code: 'T4', unit: 'µg/dL', tea: 20, src: 'CLIA 2024', dec: 1 },
    { name: 'Total T3', code: 'T3', unit: 'ng/dL', tea: 30, src: 'CLIA 2024', dec: 0 },
    { name: 'Cortisol', code: 'CORT', unit: 'µg/dL', tea: 20, src: 'CLIA 2024', dec: 1 },
    { name: 'β-hCG', code: 'HCG', unit: 'mIU/mL', tea: 18, src: 'CLIA 2024 (±18% or 3)', dec: 1 },
    { name: 'Prolactin', code: 'PRL', unit: 'ng/mL', tea: 20, src: 'CLIA 2024', dec: 1 },
    { name: 'FSH', code: 'FSH', unit: 'mIU/mL', tea: 18, src: 'CLIA 2024', dec: 2 },
    { name: 'LH', code: 'LH', unit: 'mIU/mL', tea: 20, src: 'CLIA 2024', dec: 2 },
    { name: 'Estradiol (E2)', code: 'E2', unit: 'pg/mL', tea: 30, src: 'CLIA 2024', dec: 0 },
    { name: 'Progesterone', code: 'PROG', unit: 'ng/mL', tea: 25, src: 'CLIA 2024', dec: 2 },
    { name: 'Testosterone', code: 'TESTO', unit: 'ng/dL', tea: 30, src: 'CLIA 2024', dec: 0 },
    { name: 'PTH (Intact)', code: 'PTH', unit: 'pg/mL', tea: 30, src: 'CLIA 2024', dec: 1 },
    { name: 'Ferritin', code: 'FERR', unit: 'ng/mL', tea: 20, src: 'CLIA 2024', dec: 1 },
    { name: 'Vitamin B12', code: 'B12', unit: 'pg/mL', tea: 25, src: 'CLIA 2024', dec: 0 },
    { name: 'Folate', code: 'FOL', unit: 'ng/mL', tea: 30, src: 'CLIA 2024', dec: 1 },
    { name: '25-OH Vitamin D', code: 'VITD', unit: 'ng/mL', tea: 25, src: 'Internal / VDSP', dec: 1 },
    { name: 'Insulin', code: 'INS', unit: 'µIU/mL', tea: 20, src: 'Internal / BV', dec: 1 },
    { name: 'Troponin I (hs)', code: 'TNI', unit: 'ng/L', tea: 30, src: 'CLIA 2024', dec: 1 },
    { name: 'NT-proBNP', code: 'BNP', unit: 'pg/mL', tea: 30, src: 'CLIA 2024', dec: 0 },
    { name: 'Procalcitonin', code: 'PCT', unit: 'ng/mL', tea: 20, src: 'Internal', dec: 2 },
    { name: 'IgG', code: 'IGG', unit: 'mg/dL', tea: 20, src: 'CLIA 2024', dec: 0 },
    { name: 'IgA', code: 'IGA', unit: 'mg/dL', tea: 15, src: 'CLIA 2024', dec: 0 },
    { name: 'IgM', code: 'IGM', unit: 'mg/dL', tea: 20, src: 'CLIA 2024', dec: 0 },
    { name: 'Complement C3', code: 'C3', unit: 'mg/dL', tea: 15, src: 'CLIA 2024', dec: 0 },
    { name: 'Complement C4', code: 'C4', unit: 'mg/dL', tea: 20, src: 'CLIA 2024', dec: 1 },
  ]},
  { dept: 'دلالات الأورام', tests: [
    { name: 'Total PSA', code: 'PSA', unit: 'ng/mL', tea: 20, src: 'CLIA 2024 (±20% or 0.2)', dec: 2 },
    { name: 'Free PSA', code: 'FPSA', unit: 'ng/mL', tea: 20, src: 'Internal', dec: 2 },
    { name: 'CEA', code: 'CEA', unit: 'ng/mL', tea: 15, src: 'CLIA 2024 (±15% or 1.0)', dec: 2 },
    { name: 'AFP', code: 'AFP', unit: 'ng/mL', tea: 20, src: 'CLIA 2024', dec: 1 },
    { name: 'CA 125', code: 'CA125', unit: 'U/mL', tea: 20, src: 'CLIA 2024', dec: 1 },
    { name: 'CA 15-3', code: 'CA153', unit: 'U/mL', tea: 20, src: 'CLIA 2024', dec: 1 },
    { name: 'CA 19-9', code: 'CA199', unit: 'U/mL', tea: 20, src: 'CLIA 2024', dec: 1 },
  ]},
  { dept: 'الغازات والإلكتروليتات (POCT)', tests: [
    { name: 'pH', code: 'PH', unit: '', tea: 0.5, src: 'CLIA 2024 (±0.04 @7.40)', dec: 3 },
    { name: 'pCO2', code: 'PCO2', unit: 'mmHg', tea: 8, src: 'CLIA 2024 (±8% or 5 mmHg)', dec: 1 },
    { name: 'pO2', code: 'PO2', unit: 'mmHg', tea: 15, src: 'CLIA 2024 (±15% or 15 mmHg)', dec: 1 },
    { name: 'Ionized Calcium', code: 'ICA', unit: 'mmol/L', tea: 8, src: 'Internal / BV', dec: 2 },
    { name: 'Lactate (BG)', code: 'BGLAC', unit: 'mmol/L', tea: 15, src: 'Internal', dec: 1 },
  ]},
  { dept: 'مراقبة الأدوية العلاجية (TDM)', tests: [
    { name: 'Digoxin', code: 'DIG', unit: 'ng/mL', tea: 15, src: 'CLIA 2024 (±15% or 0.2)', dec: 2 },
    { name: 'Vancomycin', code: 'VANC', unit: 'µg/mL', tea: 15, src: 'CLIA 2024 (±15% or 2)', dec: 1 },
    { name: 'Valproic Acid', code: 'VPA', unit: 'µg/mL', tea: 20, src: 'CLIA 2024', dec: 1 },
    { name: 'Phenytoin', code: 'PHT', unit: 'µg/mL', tea: 15, src: 'CLIA 2024', dec: 1 },
    { name: 'Carbamazepine', code: 'CBZ', unit: 'µg/mL', tea: 20, src: 'CLIA 2024', dec: 1 },
    { name: 'Tacrolimus', code: 'TAC', unit: 'ng/mL', tea: 20, src: 'CLIA 2024', dec: 1 },
    { name: 'Gentamicin', code: 'GENT', unit: 'µg/mL', tea: 25, src: 'CLIA 2024', dec: 1 },
  ]},
];
